import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { verifyToken } from "@/lib/auth";
import { redirect } from "next/navigation";

const ibm = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isValidUser = await verifyToken();
  console.log(isValidUser);

  if (!isValidUser) {
    redirect("/login");
  }
  return (
    <html lang="en">
      <body className={`${ibm.className} antialiased`}>{children}</body>
    </html>
  );
}
