name: CI/CD for Medichoice.Ai deployment(currently backend)

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/ci-cd.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/ci-cd.yml"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      # - name: Lint
      #   run: npm run lint
      #   working-directory: ./backend

      # - name: Build NestJS backend API
      #   run: npm run build
      #   working-directory: ./backend
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, '#deploy')
    steps:
      - name: Trigger and deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
